### PR TITLE
Add support for CH32V203C6 and CH32V203C6

### PR DESCRIPTION
**Pull request by redstonee**
it probably works

### CODE REVIEW

**Comment by maxgerhardt** [comment]
Nice work, but please PR against https://github.com/openwch/arduino_core_ch32/pulls, I'm only keeping a fork of this repo to add PlatformIO builder logic, not add on new variants.

**Comment by redstonee** [comment]
That's what I was gonna do as well, however the maintainer of that repo seems too busy to have a look at it because there are some early PRs which are still open:(

**Comment by maxgerhardt** [comment]
Then we can look at it here, but I'd still want you to open a PR there so that it's at least in their work queue.

**Comment by redstonee** [comment]
OK, thanks a lot by the way

**Pull request closed without merging**
